# Homework 0

The goal of this homework is to practice the skills learned in Lecture 2. These skills will be essential for the rest of this course.

Before starting to work on this homework, **make a new folder** named ```hw0-submission```   in your private repo and move ```Homework-0.ipynb``` into that folder.

Let's make sure that you placed everything in the correct folder

In [1]:
import os
error = False

if os.path.basename(os.path.realpath('.')) != "hw0-submission":
    print("The name of the current directory should be 'hw0-submission'")
    error = True

if not error:
    print("You did everything correctly. Congrats!")

You did everything correctly. Congrats!


Now, assuming that everything is in their correct place, you should ``git add`` all the new directories/files and make your initial ```git commit```.

## This is a Markdown cell

Insert and edit your own markdown cell *below*. Write your favorite quote.

In [2]:
# This is a code cell. Try executing it. Do not clear your output.
print("hi")

hi


Write a function that takes as argument a string and returns its 3-letter suffix. If the string is shorter than 3 letters, return the whole string.

In [4]:
def suffix_3(string):
    """
    Returns the 3-letter suffix.
    
    Parameters:
        string: str
    
    Returns:
        suffix: str
        If `string` is more than 3-letters long, `suffix` is its 3-letter suffix. Otherwise, `suffix` is the same as `string`.
    """
    if len(string) <= 3:
        return string
    return string[:3]

print(suffix_3("Hi!"))
print(suffix_3("Superb"))

Hi!
Sup


In [3]:
print(suffix_3("Hi!"))
print(suffix_3("Superb"))

NameError: name 'suffix_3' is not defined

When you finish with the above function, don't forget to ```add``` and ```commit``` to your local git repository.

Let's print the versions of some packages that we will be using in the future. If any of these packages are not present, ```conda install``` them. Do not clear your output.

In [5]:
import numpy
print('numpy:', numpy.__version__)

import scipy
print('scipy:', scipy.__version__)

import matplotlib
print('matplotlib:', matplotlib.__version__)

import sklearn
print('scikit-learn:', sklearn.__version__)

import pandas
print('pandas:', pandas.__version__)

numpy: 1.11.1
scipy: 0.17.1
matplotlib: 1.5.1
scikit-learn: 0.17.1
pandas: 0.18.1


Write a function that takes as argument a 2D list representing a matrix **M** and returns a boolean indicating whether **M** is an orthogonal matrix.

In [27]:
import numpy

def is_matrix_orthogonal(M):
    """
    Returns whether M is an orthogonal matrix.
    
    Parameters:
        M: 2D list
    
    Returns:
        is_orthogonal: boolean
    """
    NM = numpy.array(M)
    M_transpose = NM.transpose()
    pos_id = numpy.round_(numpy.dot(M, M_transpose))
    if numpy.array_equal(pos_id, numpy.identity(len(M))):
        return True
    return False
    
print(is_matrix_orthogonal([[1, 0], [0, -1]]))
print(is_matrix_orthogonal([[-1.2396, -4.3801, -1.7737], [-1.3121, -2.9193, -4.5496], [-2.1143, 0.0363, 0.2022]]))
print(is_matrix_orthogonal([[-0.8185, 0.5740, -0.0249], [-0.2510, -0.3183, 0.9142], [-0.5168, -0.7544, -0.4046]]))

[[1 0]
 [0 1]]
True
[[ 24.  22.   2.]
 [ 22.  31.   2.]
 [  2.   2.   5.]]
False
[[ 1. -0.  0.]
 [-0.  1. -0.]
 [ 0. -0.  1.]]
True


In [20]:
print(is_matrix_orthogonal([[1, 0], [0, -1]]))
print(is_matrix_orthogonal([[-1.2396, -4.3801, -1.7737], [-1.3121, -2.9193, -4.5496], [-2.1143, 0.0363, 0.2022]]))
print(is_matrix_orthogonal([[-0.8185, 0.5740, -0.0249], [-0.2510, -0.3183, 0.9142], [-0.5168, -0.7544, -0.4046]]))

AttributeError: 'list' object has no attribute 'transpose'

When you finish with the above function, don't forget to ```add``` and ```commit``` to your local git repository.

## Submitting

Now, you can push your changes to Github.